#!/bin/bash
set -e

# Create the second user and database using environment variables
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER "$BLENDEDCARE_DB_USER" WITH PASSWORD '$BLENDEDCARE_DB_PASSWORD';
    CREATE DATABASE "$BLENDEDCARE_DB_NAME" OWNER "$BLENDEDCARE_DB_USER";
    GRANT ALL PRIVILEGES ON DATABASE "$BLENDEDCARE_DB_NAME" TO "$BLENDEDCARE_DB_USER";
EOSQL