openapi: "3.0.3"
info:
  title: TimeRange Model
  version: "1.0"
  description: see https://www.rfc-editor.org/rfc/rfc8984.html#name-recurrence-properties

components:
  schemas:
    Event:
      type: object
      properties:
        dtstamp:
          type: string
          format: date-time
        dtstart:
          type: string
          format: date-time
        dtend:
          type: string
          format: date-time
        rrule:
          $ref: '#/components/schemas/RecurrenceRule'

    RecurrenceRule:
      type: object
      properties:
        freq:
          $ref: '#/components/schemas/Frequency'
        until:
          type: string
          format: date-time
        count:
          type: number
        interval:
          type: number
        byday:
          description: days on which to repeat
          type: array
          items:
            $ref: '#/components/schemas/Weekday'
        bymonth:
          type: array
          items:
            $ref: '#/components/schemas/MonthNum'
        bymonthday:
          description: days of the month on which to repeat
          type: array
          items:
            $ref: '#/components/schemas/MonthDayNum'


    Frequency:
      type: string
      enum:
        - SECONDLY
        - MINUTELY
        - HOURLY
        - DAILY
        - WEEKLY
        - MONTHLY
        - YEARLY

    Weekday:
      type: string
      enum:
        - MO
        - TU
        - WE
        - TH
        - FR
        - SA
        - SU

    MonthDayNum:
      type: integer
      minimum: 1
      maximum: 31

    MonthNum:
      type: integer
      minimum: 1
      maximum: 12

