openapi: "3.0.3"
info:
  title: TimeRange Model
  version: "1.0"
  description: see https://www.rfc-editor.org/rfc/rfc8984.html#name-recurrence-properties

components:
  schemas:
    Event:
      type: object
      properties:
        dtstamp:
          type: string
          format: date-time
        dtstart:
          type: string
          format: date-time
        dtend:
          type: string
          format: date-time
        rrule:
          $ref: '#/components/schemas/RecurrenceRule'

    RecurrenceRule:
      type: object
      properties:
        freq:
          $ref: '#/components/schemas/Frequency'
        until:
          type: string
          format: date-time
        count:
          type: number
        interval:
          type: number
        byday:
          description: days on which to repeat
          oneOf:
            - $ref: '#/components/schemas/Weekday'
            - $ref: '#/components/schemas/FirstWeekDay'
            - $ref: '#/components/schemas/SecondWeekDay'
            - $ref: '#/components/schemas/ThirdWeekDay'
            - $ref: '#/components/schemas/FourthWeekDay'
            - $ref: '#/components/schemas/LastWeekDay'
        bymonth:
          $ref: '#/components/schemas/MonthNum'
        bymonthday:
          description: day of the month on which to repeat
          $ref: '#/components/schemas/MonthDayNum'


    Frequency:
      type: string
      enum:
        - SECONDLY
        - MINUTELY
        - HOURLY
        - DAILY
        - WEEKLY
        - MONTHLY
        - YEARLY

    Weekday:
      description: days of the week
      type: string
      enum:
        - MO
        - TU
        - WE
        - TH
        - FR
        - SA
        - SU

    MonthDayNum:
      type: integer
      minimum: 1
      maximum: 31

    MonthNum:
      type: integer
      minimum: 1
      maximum: 12

    FirstWeekDay:
      description: first occurrence of week day, e.g. first monday
      type: string
      enum:
        - 1MO
        - 1TU
        - 1WE
        - 1TH
        - 1FR
        - 1SA
        - 1SU

    SecondWeekDay:
      description: second occurrence of week day, e.g. second monday
      type: string
      enum:
        - 2MO
        - 2TU
        - 2WE
        - 2TH
        - 2FR
        - 2SA
        - 2SU

    ThirdWeekDay:
      description: third occurrence of week day, e.g. third monday
      type: string
      enum:
        - 3MO
        - 3TU
        - 3WE
        - 3TH
        - 3FR
        - 3SA
        - 3SU

    FourthWeekDay:
      description: fourth occurrence of week day, e.g. fourth monday
      type: string
      enum:
        - 4MO
        - 4TU
        - 4WE
        - 4TH
        - 4FR
        - 4SA
        - 4SU

    LastWeekDay:
      description: last occurrence of week day, e.g. last monday
      type: string
      enum:
        - -1MO
        - -1TU
        - -1WE
        - -1TH
        - -1FR
        - -1SA
        - -1SU

