services:
  postgres:
    image: postgres:15-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 1s
      retries: 5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: more
      POSTGRES_USER: more
      POSTGRES_PASSWORD: more
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    healthcheck:
      test: [ 'CMD-SHELL', '[ "$$(redis-cli ping)" = "PONG" ]' ]
      interval: 10s
      timeout: 1s
      retries: 5
    ports:
      - "6379:6379"

  # ElasticSearch
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    restart: always
    ports:
      - "9200:9200"
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail -m 5 http://localhost:9200/_cluster/health || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 640M
        reservations:
          memory: 512M
    environment:
      discovery.type: "single-node"
      cluster.name: "more-cluster"
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms256m -Xmx512m"
      xpack.security.enabled: "false"
    volumes:
      - type: volume
        source: elastic-data
        target: /usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.2
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elastic:9200
      SERVER_BASEPATH: /kibana
      SERVER_REWRITEBASEPATH: "true"

  limesurvey:
    image: docker.io/martialblog/limesurvey:latest
    environment:
      DB_TYPE: pgsql
      DB_PORT: 5432
      DB_HOST: lime-db
      DB_PASSWORD: limesurvey
      DB_NAME: limesurvey
      DB_USERNAME: limesurvey
      ADMIN_USER: admin
      ADMIN_NAME: Admin
      ADMIN_PASSWORD: admin
    volumes:
      - type: volume
        source: limesurvey-data
        target: /var/www/html/upload/surveys
    ports:
      - "8081:8080"
    depends_on:
      - lime-db

  lime-db:
    image: postgres:14-alpine
    volumes:
      - type: volume
        source: lime-db-data
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: limesurvey
      POSTGRES_DB: limesurvey
      POSTGRES_PASSWORD: limesurvey
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 1s
      retries: 5

volumes:
  postgres-data:
  elastic-data:
  limesurvey-data:
  lime-db-data:
