nwa:
  cmd: "add"
  year: "2023"
  path: ["./studymanager", "./studymanager-core", "./studymanager-intervention","./studymanager-observation"]
  skip: ["**/*.xml","**/*.yaml","**/*.yml","**/*.sql","**/*.cmd","**/*.txt","**/*.md","**/*.json","**/*.properties","**/*.csv"]
  tmpl: "nwa.txt"