package io.redlink.more.studymanager.model.scheduler;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

@JsonIgnoreProperties(
        value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
        allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true, defaultImpl = Event.class)
@JsonSubTypes({
        @JsonSubTypes.Type(value = Event.class, name = Event.TYPE),
        @JsonSubTypes.Type(value = RelativeEvent.class, name = RelativeEvent.TYPE)
})
public interface ScheduleEvent {
    public String getType();
}
